/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;


import java.awt.*;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class StatisticJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticJPanel
     */
    
    Vector<Team> teams=new Vector<Team>();
    Vector<Integer> crieteria=new Vector<Integer>();
    int width=400,height=400,numOfTeams=0,margin=0,start=0,totalGoals=0,thickness=30;
    int totalCrieteria=0;
    int colorStep=0;//255/(int) Math.ceil((double)numOfTeams/8);
    double degreePerGoal=0;
    public StatisticJPanel(Vector<Team> v)
    {
        initComponents();
        //this.setBounds(10, 10, 100, 200);
        teams=new Vector<Team>();
        crieteria=new Vector<Integer>();
        numOfTeams=v.size();
        for(Team team :v)
        {
            teams.add(team);
            crieteria.add(team.goalFor);
            totalGoals+=team.goalFor;
        }
        colorStep=255/(int) Math.ceil((double)numOfTeams/8);
        margin=height/(2*numOfTeams);
        degreePerGoal=(double)((double) 360/(double)totalGoals);
    }
    // a new constructur for additional statistics on the teams
    // it is a generic constructur witch will take any other crieteria (not just goals) and show statistic
        public StatisticJPanel(Vector<Team> v,Vector <Integer> criet)
    {
        initComponents();
        //this.setBounds(10, 10, 100, 200);
        teams=new Vector<Team>();
        crieteria=new Vector<Integer>();
        numOfTeams=v.size();
        for(int i=0;i<v.size();i++)
        {
            teams.add(v.get(i));
            crieteria.add(criet.get(i));
            totalCrieteria+=criet.get(i);
        }
        colorStep=255/(int) Math.ceil((double)numOfTeams/8);
        margin=height/(2*numOfTeams);
        degreePerGoal=(double)((double) 360/(double)totalCrieteria);
    }
    public StatisticJPanel() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g)
    {
        //teamsNamePanel=new JPanel();
        teamsNamePanel.setVisible(true);
        teamsNamePanel.setLayout(new GridLayout(0,1,10,calculateVerticalGap()));
         super.paintComponent(g);
        g.drawString("total Goals :"+totalGoals, 150, 30);
        JLabel[] teamsLabel=new JLabel[numOfTeams];
        for(int i=0;i<numOfTeams;i++)
        {
            g.setColor(new Color(this.calculateColor(i, (byte)4),this.calculateColor(i, (byte)2),this.calculateColor(i, (byte)1)));
            g.fillRect(10,10+this.calculateY(i), thickness, thickness);
            g.fillArc(100, 75, 200, 200, start, this.calculateRange(i));
            int temp= this.calculateRange(i);
            start+=temp;
            g.setColor(Color.BLACK);
            //g.drawString(teams.get(i).getName(), 15+thickness, this.calculateY(i)+thickness-5);
            teamsLabel[i]=new JLabel();
            teamsLabel[i].setVisible(true);          
            teamsLabel[i].setText(teams.get(i).getName());
            teamsLabel[i].setBackground(Color.blue);
            teamsNamePanel.add(teamsLabel[i]);
            teamsLabel[i].setToolTipText(teams.get(i).toString());
        }
        revalidate();
    }
     //utility functions used to calculate the appropriate (x,y) cordinates of each smaal rectangel
    public int calculateY(int indexOfTeam)
    {
        int space=height-(numOfTeams*thickness)-10;
        return ((space/(numOfTeams-1))+thickness)*indexOfTeam;
    }
    public int calculateVerticalGap()
    {
        int labelThickness=20;
        int space=height-(numOfTeams*labelThickness);
        return space/(numOfTeams-1);
    }
    private int calculateRange(int indexOfTeam)
    {
        int goals=crieteria.get(indexOfTeam);
        int res=(int) ((double) goals*degreePerGoal);
        //start+=res;
        return res;
    }
    private int calculateColor(int indexOfTeam,byte color) //color=1 => blue, color=2 => green,color=4 => red (bitmast on 3 bits)
    {
        byte colorStatus=(byte) (indexOfTeam%8);
        int colorValue=0;
        if((colorStatus&color)!=0)
        {
            double temp1=(double)(indexOfTeam/8.0);
            double temp=(Math.ceil((double)(indexOfTeam/8.0)));
            colorValue=colorStep*(int)temp;
        }
        return colorValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamsNamePanel = new javax.swing.JPanel();

        javax.swing.GroupLayout teamsNamePanelLayout = new javax.swing.GroupLayout(teamsNamePanel);
        teamsNamePanel.setLayout(teamsNamePanelLayout);
        teamsNamePanelLayout.setHorizontalGroup(
            teamsNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        teamsNamePanelLayout.setVerticalGroup(
            teamsNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(teamsNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teamsNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel teamsNamePanel;
    // End of variables declaration//GEN-END:variables
}
